version: '3.8'

services:
  postgres:
    image: postgres:15.6-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: go_db
      POSTGRES_USER: go_user
      POSTGRES_PASSWORD: go_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - go_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://go_user:go_password@localhost:5432/go_db
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - go_network

networks:
  go_network:
    driver: bridge