# Generated by Django 5.1.6 on 2025-03-14 17:13

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sgf_content',
            field=models.TextField(validators=[games.models.validate_sgf]),
        ),
    ]
